Feat/send grid integration
wa1id/vinci-club pull request #25
Opened 2022-12-27 16:53 UTC by webcoderspeed

2022-12-28 15:23 UTC, wa1id requested changes

2022-12-28 15:23 UTC, wa1id commented on src/pages/api/signup.ts
> +  console.log(JSON.stringify(mailOptions))
remove console log

2022-12-28 15:23 UTC, wa1id commented on src/pages/api/signup.ts
> +    to: 'email@gmail.com',
`email` should be info@vinci-club.be

`to:` should be the client email no?

2022-12-28 15:23 UTC, wa1id commented on src/pages/api/signup.ts
> +    subject: 'subject',
subject is: "Bedankt voor uw inschrijving bij Vinci Club"

2022-12-28 15:35 UTC, wa1id commented on src/pages/api/signup.ts
> +sgMail.setApiKey(process.env.SENDGRID_API_KEY as string);
`SENDGRID_API`

2022-12-29 03:45 UTC, webcoderspeed commented on src/pages/api/signup.ts
> +    to: 'email@gmail.com',
as we sending it to client then yes we have to client email at [ to: client_email ]. also we need to design the template for mail

2023-01-07 13:47 UTC, wa1id commented on src/pages/api/signup.ts
> +    templateId: process.env.CLIENT_TEMPLATE_ID,
Can we set the template ID directly here? The SENDGRID_API key protects it anyways.
`d-499d3dc411d94157bb39052aa415fc53`

2023-01-07 13:50 UTC, wa1id commented on src/pages/api/signup.ts
> +    html: message,
What does this mean? `message` is just set to a string?

2023-01-07 14:01 UTC, webcoderspeed commented on src/pages/api/signup.ts
> +    html: message,
sorry I forgot we are using the template. let me push the code again

2023-01-07 14:01 UTC, webcoderspeed commented on src/pages/api/signup.ts
> +    templateId: process.env.CLIENT_TEMPLATE_ID,
okay

2023-01-07 17:01 UTC, merged