Feat/personal trainer section
wa1id/vinci-club pull request #9
Opened 2022-11-27 15:30 UTC by webcoderspeed

2022-11-27 16:28 UTC, wa1id commented
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/23665945/204146528-379eb7da-66f4-4fbd-aa23-1742fd64bec3.png">

This breakpoint is weird

2022-11-27 16:30 UTC, wa1id commented
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/23665945/204146999-095b3869-0c38-48f9-82eb-966e0a048963.png">

Can this be centered without the gap in the middle?

2022-11-27 16:31 UTC, wa1id commented
<img width="401" alt="image" src="https://user-images.githubusercontent.com/23665945/204147234-3cd10c10-3b03-4098-9a0d-c7a177535172.png">

Needs more spacing/padding on mobile

2022-11-27 16:32 UTC, wa1id commented
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/23665945/204147549-c8a7de85-def9-4833-9885-1f8c378ca680.png">
Text is overlapping. Can be underneath eachother

2022-11-27 16:39 UTC, webcoderspeed commented
yes all need to be done brother. I will work on it.

2022-11-27 16:42 UTC, wa1id requested changes

2022-11-27 16:42 UTC, wa1id commented on src/components/Card/PersonalTrainerCard.tsx
> +  const { image, name, title, description } = props;
`const PersonalTrainerCard: FC<Props> = ({ image, name, title, description })`

2022-11-27 16:42 UTC, wa1id commented on src/components/Card/PersonalTrainerCard.tsx
> +  const [readMore, setReadMore] = useState(false);
Read more will just be a link to a new page

2022-11-27 16:42 UTC, wa1id commented on src/components/PersonalTrainers/PersonalTrainers.tsx
> +            <h1 className='text-4xl md:text-7xl font-bold text-white text-center md:text-left uppercase font-drukwide'>
`<h2>` for this one since the hero page will have `h1` already

2022-11-27 16:42 UTC, wa1id commented on src/components/PersonalTrainers/PersonalTrainers.tsx
> +            </h1>
Can it be extracted to a component called `Heading` or something similar. It will be used multiple times

2022-11-27 16:42 UTC, wa1id commented on src/components/PersonalTrainers/PersonalTrainers.tsx
> +              Its ultimate aim is to help individuals and businesses in the
Add todo comment `// todo: i18n` so it will be easier to find these strings later as the text needs to be replaced

2022-11-29 14:40 UTC, wa1id approved these changes

2022-11-29 14:41 UTC, merged